name = "KoebeRealizations"
uuid = "1c1e9a7a-91ff-4d2d-990c-30114622bf37"
authors = ["mbelotti <belotti@math.tu-berlin.de>",
	"Sascha Timme <sascha@timme.xyz>"]
version = "0.1.1"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polymake = "d720cf60-89b5-51f5-aff5-213f193123e7"

[compat]
ModelingToolkit = "5.16.0"
NonlinearSolve = "0.3.8"
Plots= "1.12.0"
Polymake="0.9.0"

